import '../layout';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-yellow-50">
          <Sidebar />
          <div className="lg:pl-64 min-h-screen transition-all duration-300">
            <Navbar />
            <main className="">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}