import '../layout';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Navbar } from '@/components/Navbar';
import Sidebar from '@/components/Sidebar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="min-h-screen bg-gray-50/50">
              <Sidebar />
              
              <div className="lg:pl-64 transition-all duration-300">
                <Navbar />
        
                <main className="p-8 max-w-7xl mx-auto">
                {children}

                </main>
              </div>
            </div>

        </body>
    </html>
  );
}
